### ISSUE TITLE
Warning emitted on Ruby 2.7.3 when using memoize

### ISSUE THREAD

**Issue by paul** [dry-rb/dry-core#57] opened 2021-06-21 17:58 UTC
## Describe the bug

This wasn't an issue in 0.5.0, but when we upgraded to 0.6.0 we started getting lots of warnings from using `#memoize` on methods that take no args:

> warning: Skipping set of ruby2_keywords flag for foo (method accepts keywords or method does not accept argument splat)

## To Reproduce

Provide detailed steps to reproduce, **an executable script would be best**.

```
pry(main)> class MyClass
pry(main)*   include Dry::Core::Memoizable
pry(main)*   def foo; end
pry(main)*   memoize(:foo)
pry(main)* end
/home/rando/.gem/ruby/2.7.3/gems/dry-core-0.6.0/lib/dry/core/memoizable.rb:78: warning: Skipping set of ruby2_keywords flag for foo (method accepts keywords or method does not accept argument splat)
=> MyClass
```

## Expected behavior

No warnings emitted.

## My environment

- Affects my production application: **YES**
- Ruby version: 2.7.3
- OS: Fedora 33, OSX, whatever Heroku is running
- Dry::Core 0.6.0

**Comment by paul** [comment] 2021-06-21 18:01
Actually, looks like this was just fixed in #55? https://github.com/dry-rb/dry-core/commit/475860e1f15c4dec5fa394add9aa7d2ab73016c9#diff-f052cd3127061cb1d33e01b7d13ccc29540371b3ec02b5e373c6dab0a7acb6bbR67

**Comment by flash-gordon** [comment] 2021-06-21 19:01
I'm pretty sure it is. I'd cut a new version already but I'd like to have this merged first https://github.com/ruby/ruby/pull/4574

**Comment by solnic** [comment] 2021-06-22 07:57
Yes I can confirm that it's addressed in master.

**Comment by thetizzo** [comment] 2021-07-07 16:52
It looks like https://github.com/ruby/ruby/pull/4574 has been merged.  Would it be possible to get a cut a new version to get this issue fix out in the wild?

Thanks for the great work!

**Comment by flash-gordon** [comment] 2021-07-08 08:33
@thetizzo thanks for the heads up! I pushed 0.7.0, it should fix the warnings

**Closed** 2021-07-08 08:34 UTC
Labels: bug, help wanted
